library(mosaic)
sclass = read.csv("~/Downloads/ECO395M-master/data/sclass.csv")
summary(sclass)

# Forming two different datasets based on the given two trim levels 

sclass350 = subset(sclass, trim == '350')
summary(sclass350)

sclass65AMG = subset(sclass, trim == '65 AMG')
summary(sclass65AMG)

library(tidyverse)
library(FNN)

# Make a train-test split

N2 = nrow(sclass65AMG)
N_train2 = floor(0.8*N2)
N_test2 = N2 - N_train2

# Drawing a random sample and forming the train and test datasets

train2 = sample.int(N2, N_train2, replace=FALSE)

d_train2 = sclass350[train2,]
d_test2 = sclass350[-train2,]

nrow(d_train2)

d_test2 = arrange(d_test2, mileage)
head(d_test2)

X_train2 = select(d_train2, mileage)
y_train2 = select(d_train2, price)
X_test2 = select(d_test2, mileage)
y_test2 = select(d_test2, price)

# Running K-nearest neighbours for different values of k and finding predicted prices

pred_001 = knn.reg(X_train2, X_test2, y_train2, k=1)
pred_005 = knn.reg(X_train2, X_test2, y_train2, k=5)
pred_010 = knn.reg(X_train2, X_test2, y_train2, k=10)
pred_015 = knn.reg(X_train2, X_test2, y_train2, k=15)
pred_025 = knn.reg(X_train2, X_test2, y_train2, k=25)
pred_050 = knn.reg(X_train2, X_test2, y_train2, k=50)
pred_075 = knn.reg(X_train2, X_test2, y_train2, k=75)
pred_100 = knn.reg(X_train2, X_test2, y_train2, k=100)
pred_125 = knn.reg(X_train2, X_test2, y_train2, k=125)
pred_150 = knn.reg(X_train2, X_test2, y_train2, k=150)
pred_175 = knn.reg(X_train2, X_test2, y_train2, k=175)
pred_200 = knn.reg(X_train2, X_test2, y_train2, k=200)


ypred_k1 = pred_001$pred
ypred_k5 = pred_005$pred
ypred_k10 = pred_010$pred
ypred_k15 = pred_015$pred
ypred_k25 = pred_025$pred
ypred_k50 = pred_050$pred
ypred_k75 = pred_075$pred
ypred_k100 = pred_100$pred
ypred_k125 = pred_125$pred
ypred_k150 = pred_150$pred
ypred_k175 = pred_175$pred
ypred_k200 = pred_200$pred

# Plots of test data with predicted prices different values of k

library(gridExtra)

p_test = ggplot(data = d_test2) + geom_point(mapping = aes(x = mileage, y = price), color='purple') + theme_bw(base_size=8) + labs(x = "Mileage", y = "Price") + scale_x_continuous(breaks = scales::pretty_breaks(n = 5), labels = scales::comma) + scale_y_continuous(breaks = scales::pretty_breaks(n = 6), labels = scales::comma)


p11 = p_test + geom_path(aes(x = mileage, y = ypred_k1), color='orange') + labs(title = "k=1")


p22 = p_test + geom_path(aes(x = mileage, y = ypred_k5), color='orange') + labs(title = "k=5")


p33 = p_test + geom_path(aes(x = mileage, y = ypred_k10), color='orange') + labs(title = "k=10")


p44 = p_test + geom_path(aes(x = mileage, y = ypred_k15), color='orange') + labs(title = "k=15")


p55 = p_test + geom_path(aes(x = mileage, y = ypred_k25), color='orange') + labs(title = "k=25")


p66 = p_test + geom_path(aes(x = mileage, y = ypred_k50), color='orange') + labs(title = "k=50")


p77 = p_test + geom_path(aes(x = mileage, y = ypred_k75), color='orange') + labs(title = "k=75")


p88 = p_test + geom_path(aes(x = mileage, y = ypred_k100), color='orange') + labs(title = "k=100")


p99 = p_test + geom_path(aes(x = mileage, y = ypred_k125), color='orange') + labs(title = "k=125")


p1010 = p_test + geom_path(aes(x = mileage, y = ypred_k150), color='orange') + labs(title = "k=150")


p1111 = p_test + geom_path(aes(x = mileage, y = ypred_k175), color='orange') + labs(title = "k=175")


p1212 = p_test + geom_path(aes(x = mileage, y = ypred_k200), color='orange') + labs(title = "k=200")


library(grid)

gr1 = grid.arrange(arrangeGrob(p11 + theme(legend.position="none"), p22 + theme(legend.position="none"), p33 + theme(legend.position="none"), p44 + theme(legend.position="none")), nrow=1)
gr1

gr2 = grid.arrange(arrangeGrob(p55 + theme(legend.position="none"), p66 + theme(legend.position="none"), p77 + theme(legend.position="none"), p88 + theme(legend.position="none")), nrow=1)
gr2

gr3 = grid.arrange(arrangeGrob(p99 + theme(legend.position="none"), p1010 + theme(legend.position="none"), p1111 + theme(legend.position="none"), p1212 + theme(legend.position="none")), nrow=1)
gr3

# Calculating RMSE for k values from 1 to 200 and plotting the out-of-sample RMSE against the k values

rmse = function(actual, predicted) {
  sqrt(mean((actual - predicted) ^ 2))
}

make_knn_pred = function(k = 1, training, predicting) {
pred = FNN::knn.reg(train = training["mileage"], test = predicting["mileage"], y = training$price, k = k)$pred
act  = predicting$price
rmse(predicted = pred, actual = act)
}

k = seq(1, 200, 1)

knn_tst_rmse = sapply(k, make_knn_pred, training = d_train2, predicting = d_test2)

best_k = k[which.min(knn_tst_rmse)]

knn_results = data.frame(
k,
round(knn_tst_rmse, 2)
)
colnames(knn_results) = c("k", "Test RMSE")

knitr::kable(knn_results, escape = FALSE, booktabs = TRUE)
best_k

# best_k gives the optimal value of k for which the RMSE is minimized

pp = ggplot(knn_results) + geom_path(aes(x = k, y = knn_tst_rmse), color = "aquamarine4", size = 1.5) 
pp

ppp1 = pp + labs(x = "k", y = "RMSE", title = "Out-of-sample RMSE for each value of K") + scale_x_continuous(trans = "reverse") 
ppp1
